#!/usr/bin/env python3
"""対話セッション向け「次に着手できる項目」の機械的抽出（2026-09-25 新設）。

## なぜ要るか（停滞要因分析 ⑤・H の実体）

`sweep.py` の `dispense()` は**自律ループ（GitHub Actions）向け**のキューであり、
「オーナー作業」「ブラウザ操作」を明示的に払い出しから除外する（`is_owner_only`）。
自律ループには実行できない作業なので、これは正しい設計である。

しかし対話セッション（Claudian 等）は逆で、**まさにその「オーナー作業」こそが
本来やるべき仕事**である（`docs/operations/自律ループ停滞要因_ロジックツリー分析.md` §8）。
このスクリプトは対話セッション向けに、
  ・依存が解決していて追加判断なしに着手できる（`wbs_epic.READY`）
  ・またはステータス欄が「オーナー作業／ブラウザ操作」を宣言している
作業パッケージだけを機械的に数件返す。**仕様の判断はしない**
（`wbs_epic.classify()` をそのまま使い、新しい判定ロジックを増やさない）。

## 使い方

    python automation/scripts/next_task.py                # 上位3件を表示
    python automation/scripts/next_task.py --limit 5
    python automation/scripts/next_task.py --write         # automation/NEXT_UP.md へも書き出す（B: 可視化）

## ブロッカーに当たったときの使い方（運用ルール）

1. ブロッカーの内容を `QUESTIONS.md`（仕様起因）か、対応する Issue（技術起因）へ記録する
2. 本スクリプトを実行し、上位1件に**判断せず**着手する
3. 選ばなかった残りは `automation/NEXT_UP.md` に残るので、1件終わったら再実行する

**このスクリプトの役割は「判断しないで済むようにする」ことだけ**である。
どの項目を選ぶか迷った時点で、このスクリプトの意味が無くなる。
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import wbs_epic as E  # noqa: E402
import wbs_lib as W  # noqa: E402

DEFAULT_WBS = E.DEFAULT_WBS
DEFAULT_OUTPUT = Path("automation/NEXT_UP.md")

#: `sweep.py` の `OWNER_ONLY_MARKERS` と意図的に同じ文言を使う。
#: あちらは「除外」、こちらは「対象」に使うため、関数を import して意味を反転させるより
#: 判定ロジックを独立させたほうが誤用（どちらの意味で使っているか取り違える）が起きにくい。
OWNER_ONLY_MARKERS = (
    "自律ループでは完了できない",
    "自律ループでは実施できない",
    "オーナー作業",
    "ブラウザ操作",
)


def is_owner_only(package: W.Package) -> bool:
    row = " ".join(package.cells)
    return any(m in row for m in OWNER_ONLY_MARKERS)


def pick_next(wbs: Path, limit: int) -> list[dict]:
    """READY、またはオーナー作業/ブラウザ操作を宣言している行を、行番号順に `limit` 件集める。

    行番号順にするのは WBS の並びが依存の前後関係とおおむね一致しているためで、
    優先度の判断はしていない（判断が要る並べ替えを機械にやらせない）。
    """
    packages = W.load_packages(wbs)
    candidates: list[dict] = []
    for pkg in sorted(packages.values(), key=lambda p: p.line):
        if pkg.is_done or pkg.is_dropped:
            continue
        owner_only = is_owner_only(pkg)
        state, reason = E.classify(pkg, packages)
        if not (owner_only or state == E.READY):
            continue
        candidates.append(
            {
                "id": pkg.id,
                "name": pkg.name,
                "section": pkg.section,
                "owner_only": owner_only,
                "reason": reason,
            }
        )
        if len(candidates) >= limit:
            break
    return candidates


def render(items: list[dict]) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "<!-- AUTO-GENERATED by automation/scripts/next_task.py — 手で編集しない。再実行すれば上書きされる -->",
        "# 次に着手できる項目",
        "",
        f"生成: {ts}",
        "",
        "**ブロッカーに当たったら、判断せずここの1件目に着手する。**"
        "（`docs/operations/自律ループ停滞要因_ロジックツリー分析.md` §7・§11 参照）",
        "",
    ]
    if not items:
        lines += [
            "着手可能な項目が見つかりません。",
            "（全パッケージが完了・依存待ち・仕様待ちのいずれかです。`QUESTIONS.md` の回答を待つ状況です。）",
            "",
        ]
        return "\n".join(lines)

    for i, it in enumerate(items, start=1):
        tag = "🙋 オーナー作業（対話セッションでのみ実行可能）" if it["owner_only"] else "🟢 依存解決済み"
        lines.append(f"## {i}. {it['id']}（{it['section']}）")
        lines.append(f"- {it['name']}")
        lines.append(f"- 区分: {tag}")
        lines.append(f"- 理由: {it['reason']}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="対話セッション向け次タスク抽出（判断コストの排除）")
    ap.add_argument("--wbs", type=Path, default=DEFAULT_WBS)
    ap.add_argument("--limit", type=int, default=3)
    ap.add_argument("--write", action="store_true", help=f"{DEFAULT_OUTPUT} へも書き出す（可視化）")
    ap.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = ap.parse_args()

    items = pick_next(args.wbs, args.limit)
    body = render(items)
    print(body)

    if args.write:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(body, encoding="utf-8")
        print(f"\n[書き出し完了: {args.output}]", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
